name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build Docker Image
        run: |
          docker build -t "$CI_REGISTRY_IMAGE:library-image" .
        env:
          CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}

      - name: Docker Login
        run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} ${{ secrets.CI_REGISTRY }}

      - name: Push Docker Image
        run: docker push "$CI_REGISTRY_IMAGE:library-image"
        env:
          CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}

  test-job:
    runs-on: ubuntu-latest
    needs: build-job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Tests
        run: mvn test

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.CI_REGISTRY_USER }} -p ${{ secrets.CI_REGISTRY_PASSWORD }} ${{ secrets.CI_REGISTRY }}

      - name: Run Deployment
        run: docker run -d -p 8080:80 "$CI_REGISTRY_IMAGE:library-image"
        env:
          CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}

env:
  CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
  CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
  CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
  CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}