name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: "Login to Github Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}

      - name: Build Docker Image
        run: |
          docker build . --tag ghcr.io/${{github.repository}}:latest
          docker push ghcr.io/${{github.repository}}:latest

  test-job:
    runs-on: ubuntu-latest
    needs: build-job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Run Tests
        run: mvn test

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: "Login to Github Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{github.repository}}:latest